// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/github_search_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortOption int32

const (
	SortOption_SORT_UNSPECIFIED SortOption = 0 // Default value, often used to indicate no preference or an error
	SortOption_SORT_INDEXED     SortOption = 1
)

// Enum value maps for SortOption.
var (
	SortOption_name = map[int32]string{
		0: "SORT_UNSPECIFIED",
		1: "SORT_INDEXED",
	}
	SortOption_value = map[string]int32{
		"SORT_UNSPECIFIED": 0,
		"SORT_INDEXED":     1,
	}
)

func (x SortOption) Enum() *SortOption {
	p := new(SortOption)
	*p = x
	return p
}

func (x SortOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_github_search_service_proto_enumTypes[0].Descriptor()
}

func (SortOption) Type() protoreflect.EnumType {
	return &file_proto_github_search_service_proto_enumTypes[0]
}

func (x SortOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortOption.Descriptor instead.
func (SortOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_github_search_service_proto_rawDescGZIP(), []int{0}
}

type OrderOption int32

const (
	OrderOption_ORDER_UNSPECIFIED OrderOption = 0 // Default value
	OrderOption_ORDER_ASC         OrderOption = 1
	OrderOption_ORDER_DESC        OrderOption = 2
)

// Enum value maps for OrderOption.
var (
	OrderOption_name = map[int32]string{
		0: "ORDER_UNSPECIFIED",
		1: "ORDER_ASC",
		2: "ORDER_DESC",
	}
	OrderOption_value = map[string]int32{
		"ORDER_UNSPECIFIED": 0,
		"ORDER_ASC":         1,
		"ORDER_DESC":        2,
	}
)

func (x OrderOption) Enum() *OrderOption {
	p := new(OrderOption)
	*p = x
	return p
}

func (x OrderOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_github_search_service_proto_enumTypes[1].Descriptor()
}

func (OrderOption) Type() protoreflect.EnumType {
	return &file_proto_github_search_service_proto_enumTypes[1]
}

func (x OrderOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderOption.Descriptor instead.
func (OrderOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_github_search_service_proto_rawDescGZIP(), []int{1}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Sort          SortOption             `protobuf:"varint,3,opt,name=sort,proto3,enum=githubsearchservice.SortOption" json:"sort,omitempty"`
	Order         OrderOption            `protobuf:"varint,4,opt,name=order,proto3,enum=githubsearchservice.OrderOption" json:"order,omitempty"`
	PerPage       *int32                 `protobuf:"varint,5,opt,name=per_page,json=perPage,proto3,oneof" json:"per_page,omitempty"`
	Page          *int32                 `protobuf:"varint,6,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_github_search_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_github_search_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_github_search_service_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *SearchRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SearchRequest) GetSort() SortOption {
	if x != nil {
		return x.Sort
	}
	return SortOption_SORT_UNSPECIFIED
}

func (x *SearchRequest) GetOrder() OrderOption {
	if x != nil {
		return x.Order
	}
	return OrderOption_ORDER_UNSPECIFIED
}

func (x *SearchRequest) GetPerPage() int32 {
	if x != nil && x.PerPage != nil {
		return *x.PerPage
	}
	return 0
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Result              `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_github_search_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_github_search_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_github_search_service_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_github_search_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_github_search_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_github_search_service_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Result) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

var File_proto_github_search_service_proto protoreflect.FileDescriptor

const file_proto_github_search_service_proto_rawDesc = "" +
	"\n" +
	"!proto/github_search_service.proto\x12\x13githubsearchservice\"\x80\x02\n" +
	"\rSearchRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x123\n" +
	"\x04sort\x18\x03 \x01(\x0e2\x1f.githubsearchservice.SortOptionR\x04sort\x126\n" +
	"\x05order\x18\x04 \x01(\x0e2 .githubsearchservice.OrderOptionR\x05order\x12\x1e\n" +
	"\bper_page\x18\x05 \x01(\x05H\x00R\aperPage\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x06 \x01(\x05H\x01R\x04page\x88\x01\x01B\v\n" +
	"\t_per_pageB\a\n" +
	"\x05_page\"G\n" +
	"\x0eSearchResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.githubsearchservice.ResultR\aresults\"7\n" +
	"\x06Result\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo*4\n" +
	"\n" +
	"SortOption\x12\x14\n" +
	"\x10SORT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fSORT_INDEXED\x10\x01*C\n" +
	"\vOrderOption\x12\x15\n" +
	"\x11ORDER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tORDER_ASC\x10\x01\x12\x0e\n" +
	"\n" +
	"ORDER_DESC\x10\x022h\n" +
	"\x13GithubSearchService\x12Q\n" +
	"\x06Search\x12\".githubsearchservice.SearchRequest\x1a#.githubsearchservice.SearchResponseB3Z1github.com/Pratham700/github-search-service/protob\x06proto3"

var (
	file_proto_github_search_service_proto_rawDescOnce sync.Once
	file_proto_github_search_service_proto_rawDescData []byte
)

func file_proto_github_search_service_proto_rawDescGZIP() []byte {
	file_proto_github_search_service_proto_rawDescOnce.Do(func() {
		file_proto_github_search_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_github_search_service_proto_rawDesc), len(file_proto_github_search_service_proto_rawDesc)))
	})
	return file_proto_github_search_service_proto_rawDescData
}

var file_proto_github_search_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_github_search_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_github_search_service_proto_goTypes = []any{
	(SortOption)(0),        // 0: githubsearchservice.SortOption
	(OrderOption)(0),       // 1: githubsearchservice.OrderOption
	(*SearchRequest)(nil),  // 2: githubsearchservice.SearchRequest
	(*SearchResponse)(nil), // 3: githubsearchservice.SearchResponse
	(*Result)(nil),         // 4: githubsearchservice.Result
}
var file_proto_github_search_service_proto_depIdxs = []int32{
	0, // 0: githubsearchservice.SearchRequest.sort:type_name -> githubsearchservice.SortOption
	1, // 1: githubsearchservice.SearchRequest.order:type_name -> githubsearchservice.OrderOption
	4, // 2: githubsearchservice.SearchResponse.results:type_name -> githubsearchservice.Result
	2, // 3: githubsearchservice.GithubSearchService.Search:input_type -> githubsearchservice.SearchRequest
	3, // 4: githubsearchservice.GithubSearchService.Search:output_type -> githubsearchservice.SearchResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_github_search_service_proto_init() }
func file_proto_github_search_service_proto_init() {
	if File_proto_github_search_service_proto != nil {
		return
	}
	file_proto_github_search_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_github_search_service_proto_rawDesc), len(file_proto_github_search_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_github_search_service_proto_goTypes,
		DependencyIndexes: file_proto_github_search_service_proto_depIdxs,
		EnumInfos:         file_proto_github_search_service_proto_enumTypes,
		MessageInfos:      file_proto_github_search_service_proto_msgTypes,
	}.Build()
	File_proto_github_search_service_proto = out.File
	file_proto_github_search_service_proto_goTypes = nil
	file_proto_github_search_service_proto_depIdxs = nil
}
